# Site Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Site Information
locale: "en-US"
title: "Ziyu Xiang"
title_separator: "-"
subtitle: "PhD Student in Physics at UC Berkeley"
name: "Ziyu Xiang (向子钰)"
description: "Ziyu Xiang - PhD student in Physics at UC Berkeley studying strongly correlated 2D electron systems with scanning tunneling microscopy. Research in quantum many-body phenomena, moiré superlattices, and 2D materials."
url: "https://zyxiang6.github.io"
baseurl: ""
repository: "zyxiang6/zyxiang6.github.io"
teaser: /assets/images/ziyu-headshot.jpg
logo: 
masthead_title: "Ziyu Xiang"
breadcrumbs: false
words_per_minute: 200
enable_copy_code_button: true

# Site Search
search: true
search_full_content: true
search_provider: lunr

# Site Author
author:
  name: "Ziyu Xiang"
  avatar: "/assets/images/ziyu-full.jpg"
  bio: "PhD Student in Physics at UC Berkeley"
  location: "Berkeley, CA"
  email: "zyxiang@berkeley.edu"
  uri: "https://zyxiang6.github.io"
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=-bXvJDMAAAAJ&hl=en"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-3954-7631"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Ziyu-Xiang-6"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ziyu-xiang-8481292b3/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zyxiang6"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zyxiang6"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=-bXvJDMAAAAJ&hl=en"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Ziyu-Xiang-6"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ziyu-xiang-8481292b3/"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-3954-7631"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:zyxiang@berkeley.edu"

# Reading Files
include:
  - .htaccess
  - _pages
  - google447df939a6ff470b.html
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - node_modules
  - package.json
  - tmp
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Pagination
paginate: 5
paginate_path: /page:num/

# Posts on homepage
show_excerpts: false
paginate_path: /posts/page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: false
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      toc: false

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Google Search Console verification
google_site_verification: "447df939a6ff470b"

# SEO settings
social:
  type: Person
  name: "Ziyu Xiang"
  links:
    - "https://scholar.google.com/citations?user=-bXvJDMAAAAJ&hl=en"
    - "https://orcid.org/0000-0002-3954-7631"
    - "https://www.researchgate.net/profile/Ziyu-Xiang-6"
    - "https://www.linkedin.com/in/ziyu-xiang-8481292b3/"
    - "https://github.com/zyxiang6"

# Additional SEO
tagline: "PhD Student in Physics at UC Berkeley"
keywords: "Ziyu Xiang, physics, quantum, 2D materials, scanning tunneling microscopy, UC Berkeley"

# Feed settings
feed:
  posts_limit: 20
  excerpt_only: true

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: # Add your Google Analytics ID here if you have one
